### ISSUE TITLE
Screenshot feature very unstable

### ISSUE THREAD

**Issue by JerwuQu** [Reisyukaku/ReiNand#14]
It more often freezes the console than actually taking a screenshot. (n3ds v10.3)

**Comment by aroth-khashar** [comment]
The screenshot code has hard-coded offsets that, iirc, currently correspond to the core Pokemon games. If you are using it somewhere else that is probably why.

**Comment by JerwuQu** [comment]
Ah, I see. So then would it be able to take screenshots in other applications too? Iirc HANS is able to? Or does HANS know exactly where those offsets will be?

**Comment by ghost** [comment]
HANS uses a different method iirc, since it uses ARM11.
