### ISSUE TITLE
Black screen at boot?

### ISSUE THREAD

**Issue by ghost** [Reisyukaku/ReiNand#15]
I have a Japanese N3DS (Not LL) with sysNAND 9.1 and no emuNAND installed. Will I need to install emuNAND for this to work? Im using the latest version.

**Comment by aroth-khashar** [comment]
Yes, The default boot behavior is to attempt to launch emunand.

**Comment by ghost** [comment]
How do I set it to sysNAND?

**Comment by aroth-khashar** [comment]
I believe you can hold B when you press Start at the splash screen to load into sysnand.

**Comment by aroth-khashar** [comment]
Keep in mind that this functionality is missing if you are using a modified build that autoboots, and I think @Reisyukaku is planning to remove it in the next commit.

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
@aroth-khashar Whenever I start the ReiNand.dat or ReiNand.3dsx I get a black screen with nothing prompting me to press start. What am I doing wrong? Heres my filesystem (minus alot of unrelated stuff)

```
├── boot.3dsx
├── rei
│   ├── emunand
│   │   └── emunand.bin
│   ├── firmware.bin
│   ├── splash.bin
│   └── thread
│       └── arm9.bin
├── ReiNand.3dsx
├── reiNand.dat
├── ropbinpayload_menuhax_JPN14336_new3ds.bin
├── ropbinpayload_menuhax_JPN25600_new3ds.bin
├── slot0x11key96.bin
```

**Comment by aroth-khashar** [comment]
I have not been successful getting the .3dsx file to boot. How are you launching the dat file?

**Comment by aroth-khashar** [comment]
For reference, I use ctrbootmanager to load the dat file directly, with an offset of 0x12000

**Comment by ghost** [comment]
When I try using ctrbootmanager it says boot.cfg not detected and that its making a new one then freezes. Even though I have a boot.cfg already

**Comment by aroth-khashar** [comment]
hmm, where is your boot.cfg located? Also can you upload it so I can check the contents?

**Comment by aroth-khashar** [comment]
Try placing this file on the root of your SD card and renaming it to boot.cfg, then booting with ctrbootmanager.

[boot.txt](https://github.com/Reisyukaku/ReiNand/files/92727/boot.txt)

**Comment by ghost** [comment]
I seem to have got it working. But for some weird reason when I went into emuNAND with reiNAND then used browserhax to goto FBI, CIAs still say invalid signature.

**Comment by aroth-khashar** [comment]
What version is your emunand on?

You cannot use the .3dsx version of FBI on 9.3+, period. Doesn't matter if you are on emunand or have signature checks disabled. On 9.3+ *hax does not provide the level of permissions needed to install cias (signed or unsigned, doesn't matter) at those firmwares it only has arm11 userland access.

**Comment by ghost** [comment]
Yeah I realized I was an idiot and forgot to install a CIA manager before updating -_- Now I might have to reinstall emuNAND

**Comment by ghost** [comment]
Oh and @aroth-khashar I think there's a (experimental) FBI build that has memchunkhax which might fix my problem
