### ISSUE TITLE
[Feature Req.] Region Free

### ISSUE THREAD

**Issue by NULLx76** [Reisyukaku/ReiNand#16]
I would like if ReiNand would add a RegionFree patch. So we can play games out of your 3DS' region.

**Comment by aroth-khashar** [comment]
While this would be a nice feature to have, I must vehemently request that reinand not go the route of rxtools and sacrifice DS, DSiWare and GBA compatibility in pursuit of a feature that can be provided with an external tool. 

The things I listed CANNOT be provided by installing/running another application, whereas we can easily get access to out of region games with things like NTR and FMP.

**Comment by IAmForeverAloneToo** [comment]
Hey guys, stop annoying him with these requests over and over, in gbatemp I talked to him a while ago and he said that he's looking forward to it, so stop bothering him so much.

**Comment by IAmForeverAloneToo** [comment]
Oops sorry
