### ISSUE TITLE
Reinand 3.1 missing "Rei" string in version number

### ISSUE THREAD

**Issue by sweis12** [Reisyukaku/ReiNand#17]
With the latest release of Reinand, it no longer says "Rei X.X.X-X" It says "Ver. X.X.X-X" in system settings.
It worked fine in 3.0

**Comment by Reisyukaku** [comment]
Yea, this is a known issue. Not sure why its not working. I'll continue to look into this.

**Comment by ghost** [comment]
though it doesnt show it, is it officially on emunand?

**Comment by NathanDreamweaver** [comment]
yes.
