### ISSUE TITLE
v3.1 doesnt support 10.3 emunand?

### ISSUE THREAD

**Issue by zjxlsgh** [Reisyukaku/ReiNand#18]
i have a file called Reinand9.5+ i forget where i got that, but that one does run with10.3. so the lastest doenst? o.0

great work by all means

**Comment by sweis12** [comment]
Use 3.1 and the firmware file in the readme
3.1 got a new one. I had this issue too.

**Comment by JerwuQu** [comment]
I think this should be closed. The issue is solved by using the new firmware file.
