### ISSUE TITLE
o3DS support

### ISSUE THREAD

**Issue by Flat** [Reisyukaku/ReiNand#20]
What would have to be added/changed to ReiNand to support o3ds?

**Comment by RinMaru** [comment]
That would complicate things why not just use rxtools. Having to focus on both systems would make things harder i think its best this stay n3ds exclusive. unless the dev merges his work with rxtools.

**Comment by Flat** [comment]
It may complicate things yes, but the rxTools codebase isn't in good shape and includes regionfree which breaks support for older console games.

**Comment by Hartie95** [comment]
I don't think its regionfree that breaks it, it should be the arm11 thread they are using, but regionfree is possible using svc backdoor from arm9 thread.

**Comment by Flat** [comment]
I may be misinformed about region free breaking it then. Either way rxTools is lacking the means to run older console games.

**Comment by RinMaru** [comment]
I haven't had any issues with rxtools on launch day games but im using the 3.0 Alpha. Rxtools seems to be more actively developed then Reinand.

**Comment by Reisyukaku** [comment]
rxtools hasnt been updated in forever.. I've pushed so much code in the past few weeks lol.
Anyways i'm working on an offical port of o3ds.. i know a lot of people were getting impatient, but i needed to make things more flexible for a better port.

**Comment by RinMaru** [comment]
Rxtools has been updated the nighties are back up.

**Comment by Flat** [comment]
Wasn't trying to be a "HEY WHY IT NO WURK ON MUH 3DS" More of a "Hey what's missing maybe I can help add it" If you have any ideas on what needs to be changed maybe I can help.
