### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by Infinete** [Reisyukaku/ReiNand#21]
Whenever a game is exited the system crashes momentarily with a message "An error has occurred. Please save your data in any software currently in use. Then restart the system" "A=OK", it is then usable again. Almost like it has reached a memory/ram limit.
Firmware version doesn't matter.

**Comment by Infinete** [comment]
When it crashes it would appear to reload the home menu I believe.

**Comment by Reisyukaku** [comment]
Are you on latest build? I can't reproduce any kind of error.

**Comment by Infinete** [comment]
I decided to backup everything, emuNand included, I deleted my partition, re built the sd, re injected my emuNand and copied everything over. I then ensured I was on your latest build from your github release, and yes I still get a system crash when I exit a game via the home menu. What is odd though is that it only seems to happen when I exit a game so that the game is, for lack of a better word, lingering in the background. 

I tested this with Boot NTR, if I have to exit the program via the home menu button, the home menu crashes and reloads and thus Boot NTR is no longer loaded into the firmware and so does not work in game. If I use the auto exit version, for some reason, the home menu does not crash. I assume because the game is not lingering in the background, and so I can use the plugins in game just fine.

Is there a chance there is something wrong with my emuNAND? Or perhaps my sd size? It was happening on my 64GB and now on my 128GB both class 10. I used Gateway Launcher to make my emuNand, but I doubt that matters.

**Comment by Reisyukaku** [comment]
Does this also happen on CakesFW, etc?
You could also try commenting out the thread patch code in firm.c and compiling that. See if maybe its the thread.

**Comment by Hartie95** [comment]
Boot ntr could also be closed using start(don't know why it doesn't tell the user about this).
If its a real 64/128GB sd card, the size should not be the problem(I'm using a 64gb sd). Have you tried cakehax? Cakehax doesn't use a arm9 thread, maybe its the thread.
Also are you using the latest firm? You can find a link in this repository's readme.

**Comment by Infinete** [comment]
Interesting about the Boot NTR, none the less, pressing home menu to leave an app or program still crashes the home menu....as for cakes, I could not get cakes working to test, it did not like my firm/firm key, I will try again this afternoon, I did not have this problem on RXTools, however, that was pre 9.6+.

**Comment by Reisyukaku** [comment]
i've ran and tested reinand on 4 retail units, 3 o3ds/1 n3ds, and 1 o3ds dev unit.. cant get them to crash lol. and i havent heard anyone else have this problem yet. probably isnt the cfw. maybe theres some bad system cache? Idk, ill close for now
