### ISSUE TITLE
[Enhancement] Remove CA Verification from HTTPS

### ISSUE THREAD

**Issue by jankcat** [Reisyukaku/ReiNand#23]
I am not sure if this is possible for CFW to achieve, but if possible it would be a neat feature if the Update Service and eShop did not do Certificate Authority checks or verify that certificates were not self-signed during the HTTPS handshake. 

If this would be possible, then the next question would be the possibility of removing the signature check from the eShop. If the eShop is not checking the server certificate, and not checking if CIAs are signed by NIntendo, the eShop app with a custom hosted eShop Server could be used as an alternate to sideloading CIAs with FBI.

**Comment by Reisyukaku** [comment]
Well I've never looked at the SSL module, and its not in firm, so its something you would be better off patching via NTR if you're just doing quick hacks. Either way, you need arm11 stuff. 
Also for the eshop, eshop doesnt use AM service, so it doesnt touch CIA stuff. That's probably more of a NIM thing.

**Comment by Syphurith** [comment]
@jankcat Thanks for your idea. However the ARM11K isn't done in Rei yet. The eShop links may be in NIM or other modules, better patched through ARM11 not ARM9. _Well.._

**Comment by Hartie95** [comment]
Svc backdoor could be used, but the thread size limitation is an other problem.

**Comment by Reisyukaku** [comment]
with the current loader, this should be possible to make youself and add to patches.dat.
