### ISSUE TITLE
[Feature Req.] ReiUpdater

### ISSUE THREAD

**Issue by RinMaru** [Reisyukaku/ReiNand#24]
Would it be possible to add a feature that will let us update Reinand directly from our n3ds since the sd card is in a difficult place.

**Comment by ghost** [comment]
That's what FTP is for, no?

**Comment by ihaveamac** [comment]
microSD Management also, if using Windows

**Comment by RinMaru** [comment]
If there's a tool that does Update Reinand i was not aware but i was thinking somthing builtin to reinand that is more user friendly and less of an inconvenience.

**Comment by ihaveamac** [comment]
you'd probably still have to manually update firmware.bin (if it ever gets updated again). I don't know about that

**Comment by RinMaru** [comment]
from the sound of it firmware.bin updates are far and few between. Just somthing that handles the more rapid updates would be nice. Im on the road to buying a N3DS so the microsd management tool is new info to me.

**Comment by Syphurith** [comment]
@Zetchzie MicroSD Management Tool has been modified to run on O3DS too. _Easiest way to do so._

**Comment by RinMaru** [comment]
I did not know this. But still if your away from a computer this would be a nice feature.

**Comment by SUOlivia** [comment]
Not a bad idea maybe a homebrew app for doing this in the same way as the
custom HB launcher

**Comment by RinMaru** [comment]
It would be nice to have for those of us that travel allot and only have a wifi contection plus it would save time. And if anything changes like new folder directorys in new builds it will place them correctly.

**Comment by ghost** [comment]
Lol this would be epic, I don't even have a micro SD card reader for my computer (Linux). I have to use my phone which is difficult. Also, @tobold ftbrony gets 10kbps at most for me...

**Comment by ghost** [comment]
I have a n3ds and for these things you have both ftp (what I use) and the built-in microsd share (you can also use this in linux, just get samba and config it, many distros do this automagically)

remember the most sd writing speed,  the most speed over ftp you will get

**Comment by aroth-khashar** [comment]
@Zetchzie @s3r1alpari4h @ihaveamac 

Honestly the mSD Management tool is the best option to avoid removing the SD card. Generally better speeds than ftbrony, plus if you use the patched mSDmanagement cia file from 3dsiso you can access it from the home menu and exit without rebooting back into sysnand. Which makes it better than ftbrony even if it was the same speed. 

As for the firmware.bin, you can replace it with the mSD management tool as well since the only time the CFW actually touches the file is during launch when it loads it into ram and patches it to remove the signature checks. Just drop the new on in place and overwrite,then reboot the system.

**Comment by ihaveamac** [comment]
I noticed firmware.bin is now missing from the README. I think it's due to auto patching?

on a side note, microSD Management is not an option for me because it does not work on OSX. :/

**Comment by aroth-khashar** [comment]
@ihaveamac 

I think he made some changes in the way it does encryption so he started including the firmware.bin in the source files. Not 100% sure what this means in regards to the legality of hosting the compiled builds.

**Comment by fox8091** [comment]
If someone would like to fork this and modify it to work with ReiNAND, that would resolve this.
https://github.com/Hamcha/arnupdate
