### ISSUE TITLE
Can't boot into emuNAND

### ISSUE THREAD

**Issue by spelled-ayayron** [Reisyukaku/ReiNand#25]
I can't seem to boot into emuNAND through CTRBootmanager. I have it set to launch ReiNand.dat from CTR through menuhax, it shows the new splash, but then it hangs on a black screen with a small green pixel in the bottom left corner. The sysNAND is on 9.2, and I had just setup a fresh emuNAND through Emunand9 via HBL. The offset is 0x12000 if that means anything. Love the work, by they way. 

This is only happening on a friend's N3DSXL, as my own boots perfectly fine.

**Comment by Zetchzie** [comment]
Do you have the directories in the config file set correctly?
