### ISSUE TITLE
Not able to install CIAs on EmuNAND with 3.2-Beta

### ISSUE THREAD

**Issue by EpicLPer** [Reisyukaku/ReiNand#26]
For some reason I think the system menu patches are not applied or something.
With FBI (or any other CIA installer) I cannot install any apps to EmuNAND anymore. I simply get an error-message mentioned in the following thread here: http://gbatemp.net/threads/cia-installation-on-rei-emunand-sysnand-not-possible-after-upgrade-and-restore-of-emunand.412557/#post-6027221

I will try 3.1 now to see if it's possible to install stuff there again, I hope so because it's really annoying...
I tried installing CIAs via MiniPasta and it worked just fine.

**Comment by EpicLPer** [comment]
Okay, doesn't work with 3.1 either... Not sure if this is a problem with ReiNAND or another problem with my EmuNAND setup. But I simply can't figure out what's wrong here, I've probably tried most things to get it working again already...

**Comment by Rinnegatamante** [comment]
Looks like the problem is in ServiceAccessControl not properly patched?

Trying hblauncher_loader on an old ReiNand version resulted in am:u service accessible.
With latest version am:u service is not accessible.

Tried this using a debug version of NASA. On old ReiNand it boots fine, on latest version it tries to execute memchunkhax2 cause am:u is not accessible and then freeze (due to low bootrate on N3DS consoles the hax has, probably).

**Comment by ihaveamac** [comment]
seems the same thing is happening to me...? 10.5.0-30U emunand, kernel version reports as 2.50-9

**Comment by RinMaru** [comment]
oh boy this isnt good. Does this mean a system transfer with cias installed won't work?

**Comment by ihaveamac** [comment]
I think it's 3dsx-form CIA installers, at least with what I've tried. I was able to installing something with NASA and FBI in cia-form

**Comment by RinMaru** [comment]
so bigbluemenu still works?

**Comment by ihaveamac** [comment]
yes, I tried it too

**Comment by RinMaru** [comment]
thats good. should be getting my n3ds next month.

**Comment by EpicLPer** [comment]
I've now found a solution which is possible but rather annoying and... not recommended to be honest.
I simply cloned my SysNAND to EmuNAND once FBI was installed as app there so I now have a possible way to also install CIAs in EmuNAND, then after doing so unlinked both again with TinyFormat.

Installing CIAs works again now, however the 3DSX version still does nothing.

**Comment by Reisyukaku** [comment]
I've downgraded and installed reinand on multiple consoles and never ran into this problem. But it seems resolved so closed
