### ISSUE TITLE
reinand not working on n3ds 9.2 

### ISSUE THREAD

**Issue by YamiRioru** [Reisyukaku/ReiNand#27]
I can't get into reinand emunand and I have done everything, I got the firmware.bin, I split my sys/emunands and its not working... It keeps freezing on the splash screen, and if i do get passed it it resets into the ctrbootmanager and freezes at the boot menu once again... I don't really know what to do... I have been trying for two days trying to get my emunand fixed after I deleted a nand file in fbi like a dumbass and bricked my n3ds... I just need your help because, I really want to play some pokemon with my cousins and do some animal crossing new leaf with my girlfriend over emunand so please help me... Sincerely YamiRioru (aka DarkRiolu264 on gbatemp)

**Comment by ihaveamac** [comment]
> and if i do get passed it it resets into the ctrbootmanager and freezes at the boot menu once again...

this probably means you have menuhax in emunand. did you set a button to bypass menuhax (e.g. holding L gets you to the Home Menu)? if so, hold that as soon as you go into ReiNand.

**Comment by YamiRioru** [comment]
yes I did... i input the select... button.. when is that? after the timer into auto booting reinand or when I first turn on the 3ds?

**Comment by ihaveamac** [comment]
as soon as you enter ReiNand it's like turning on your console so you'd hold select then I guess.

**Comment by MK73DS** [comment]
I have the same issue, but I don't have menuhax (my console boots normally into the system).
I have a 9.2 n3DS EUR. And I created my emuNAND with emuNAND9
But when I launch ReiNand from the HBL, it freezes on the spash screen :( I'm using the lastest version of ReiNand, and of course I have firmware.bin in the rei folder :)

Thank's for helping :)

**Comment by ihaveamac** [comment]
are you sure it's the latest firmware.bin? I can't think of anything else that might be freezing it, though maybe Reisyukaku knows

**Comment by MK73DS** [comment]
I don't know, I downloaded it from a tutorial video on YouTube :/ In fact, I don't know where I can find that file up to date :(
But in the video he was successfuly able to run ReiNand, so I think the file is good

**Comment by ihaveamac** [comment]
a firmware.bin is linked to in the README of this repo. try that one

**Comment by MK73DS** [comment]
Wow thank you very much it works :D

**Comment by YamiRioru** [comment]
got it working, just needed to reset my memory in: system settings/data
management/ 3ds/ game memory (first top option)

**Comment by YamiRioru** [comment]
you're welcome
