### ISSUE TITLE
3D display doesn't work

### ISSUE THREAD

**Issue by dogtopus** [Reisyukaku/ReiNand#28]
ReiNAND v3.2 beta with N3DS firmware 10.5.0-30U.
When 3D is on, instead of showing 3D effects, the whole screen gets blurred.
3D works in sysNAND without ReiNAND launched. Therefore I am pretty sure it's not a hardware problem.

**Comment by ihaveamac** [comment]
this is a common problem with all custom firmwares. the temporary fix is to close and re-open the console (i.e. put in and take out of sleep mode).

**Comment by dogtopus** [comment]
That worked, thx
Still hope there will be a "proper" fix for this issue though...

**Comment by Reisyukaku** [comment]
I never use the 3D feature myself, but i feel like if i were to emulate something to fix the problem, it would have to be right after firmlaunch, which is out of the bounds of my cfw, lol. So for now ill close.
