### ISSUE TITLE
Is firmware.bin still needed for 3.2b release?

### ISSUE THREAD

**Issue by Committee** [Reisyukaku/ReiNand#29]
Topic.

**Comment by ihaveamac** [comment]
a firmware.bin is included with the .zip so you probably still need it then

**Comment by Committee** [comment]
Oh crappy fart I deleted that file I thought it was the old "firmware goes here". Thank you for the quick reply! This can be closed now.

**Comment by ihaveamac** [comment]
you can close it yourself since you made the issue ;p
