### ISSUE TITLE
3D display blurring when loaded into CFW

### ISSUE THREAD

**Issue by rk2900** [Reisyukaku/ReiNand#30]
I use ReiNand, and get into CFW using 414 operation (4th button in Setting, 1st button on menu and at last 4th button on menu then loading into CFW).
However, when I get into CFW, the 3D display is blurring, both in Home menu or in game.
It goes normal when I close the lid of my 3DS (gone into sleep mode) and open it (gone back into power on mode) again.

Is it a bug of this CFW? Or any other problems in loader?

Anybody has any idea?

Thank you!

**Comment by RinMaru** [comment]
this wont be fixed for a good while i posted the same bug on rxtools and someone has posted this bug here earlier.

**Comment by hg8** [comment]
Ref : https://github.com/Reisyukaku/ReiNand/issues/28

**Comment by Hartie95** [comment]
Since the code for fixing this is available, for example in cakes cfw, I think it will be fixed in near future.

**Comment by gambit3rd** [comment]
It's 3 days that the fix available in AuReiNand (ReiNand Mod) too. Credits to TiniVi and Cakes.

Hope that someone will port the fix here too. :)

**Comment by Reisyukaku** [comment]
To be honest, i'd rather completely disable the 3D feature all together then to fix it lol.

**Comment by gambit3rd** [comment]
Lol, I recall you already stated your position about the 3D feature. XD

Anyhow, thanks for your wonderful work: 3D or not. :)

**Comment by Reisyukaku** [comment]
ill push a fix either way in the next push.. so look out for that
