### ISSUE TITLE
[Feature Req.] SysNAND support with arm9loaderhax

### ISSUE THREAD

**Issue by RomLecat** [Reisyukaku/ReiNand#31]
It would be nice to be able to use ReiNAND on SysNAND using arm9loaderhax.

Also, if it could have different version strings if we're on EmuNAND or SysNAND, that would be perfect,  like RxTools is doing it (Rx-E for EmuNAND and Rx-S for SysNAND).

**Comment by Reisyukaku** [comment]
It already has that though..?
https://github.com/Reisyukaku/ReiNand/blob/master/source/firm.c#L51

**Comment by RomLecat** [comment]
How do we boot to SysNAND then ? Does it have FIRM write protection so we can update it without erasing A9LH ?

And finally, do you plan to patch version string ?

**Comment by Reisyukaku** [comment]
Hold start to bypass emunand patches.. therefore its firmlaunched  sys. Also since its firmlaunching, i guess its protected.. ? no idea tbh. never tried.
Version string is patched on both still.

**Comment by RomLecat** [comment]
Oh, didn't know. A nice feature would to have a file to permanent trigger this so we can always boot on SysNAND. Others CFW needs patches to be safe against updates, so I think ReiNAND too ?

Also, I meant different version strings if we're on EmuNAND or SysNAND. That would be helpful.
