### ISSUE TITLE
Commit: d9d4bfd30c19c04996dfd7e9099282a76f673c75 won't run

### ISSUE THREAD

**Issue by ItsYogSothoth** [Reisyukaku/ReiNand#33]
N3DS 9.2.0-20E sysnand
build cakehax version
It's getting stuck on splash screen. Checked on both *hax 2.5 and *hax 2.6
No matter if runned from CtrBootManager or Homebrew Launcher app.

**Comment by Reisyukaku** [comment]
you copied all files over to root of SD card? and didnt add or modify anything? because it should work out of the box, but some people mess with the firmware.bin for some reason.

**Comment by ItsYogSothoth** [comment]
Copied everything that was in out folder to root of SD card.
I forgot to mention I'm using 10.6 EmuNAND and menuhax to run CtrBootManager
