### ISSUE TITLE
Sleep mode bug {smash bros.}

### ISSUE THREAD

**Issue by phant0mg33k** [Reisyukaku/ReiNand#34]
I have had this issue persistently appears when playing smash. If i am using a amiibo and playing a standard match, and close the lid of the device after pressing start and putting the system to sleep. The device will not wake up from sleep mode. you can close the lid open it multiple times yet nothing. Pressing any buttons as well does nothing. To get the device back on and functional it needs to be reset via the power button. This issue happens when running Reinand 3.3. NON A9LH 10.6[U] Emunand.
Issue never happen as of 3.2 Reinand 10.6[u]. This issue happens with either normal smash4 or even running Salty SD in smash4 as well. If it helps this is running on a NEW3dsXL.

**Comment by Lumince** [comment]
Have you tried a fresh emunand? I had an issue and starting from scratch fixed it. I also recommend installing a9hl. If you follow the guide letter by letter it works. I was scared to do so but forced myself to follow it slowly and it installed with no problem.

**Comment by Reisyukaku** [comment]
should have fixed, will close for now
