### ISSUE TITLE
ReiNand does not work on a9lh updated sysNand?

### ISSUE THREAD

**Issue by nobitagamer** [Reisyukaku/ReiNand#43]
I have a9lh with updated sysNand 10.7.0-32U (also deleted emuNand) and cannot make ReiNand to work.

**Comment by Reisyukaku** [comment]
Works for me on a clean card. Maybe you didnt wipe the card completely, so theres a NCSD fragment

**Comment by nobitagamer** [comment]
Sorry but what does 'NCSD fragment' mean and what i can do to make ReiNand work on my N3DS.

**Comment by Reisyukaku** [comment]
Emunand detection works by locating the NCSD header, and when you format an SD or delete things, it only deletes the pointers to the file, but the data is still written to the raw sectors, so you probably still have parts of emunand still written to your card and its being fooled.. if you're using windows, try getting HPUSBDISK and running that to format your card (back stuff up first as needed.). Unchecking 'quick format' should make it write 00s to those sectors i'd assume

**Comment by nobitagamer** [comment]
I tried checkout your source, comment out the 'Check for Emunand' in firm.c and rebuild to test but still no luck.

**Comment by Reisyukaku** [comment]
Not surprised at all, because its not the code. I've already given a solution to the problem as i've tested it myself before even posting.
