### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by fox8091** [Reisyukaku/ReiNand#44]
I'm sorry to bring this up, but your "Legal ambiguity update" commit did not fully fix the issue of GPL compliance. By having "All rights reserved" in the headers of your files, those files are not included in the GPL licensing. Thought I would let you know. :)

**Comment by fox8091** [comment]
Also, feel free to close this once said issue is addressed. :)

**Comment by Reisyukaku** [comment]
I'm gonna listen to my lawyer friend before a rando on the internet, but thanks for the concern.

**Comment by ghost** [comment]
Sorry, I saw you mention lawers, you know a good one?
I need to defend my waifu.

**Comment by laramie14** [comment]
Suing for someone editing a file you put online? Good luck XD that's just about as bad as stealing someone's Skype password and breaking into a Skype conversation. XD
