### ISSUE TITLE
Can't build with updated ctrulib [2810c4d] [f22b8f7] [c81239a]

### ISSUE THREAD

**Issue by PeggerWed** [Reisyukaku/ReiNand#49]
If you update ctrulib to latest commit [2810c4d] [f22b8f7] [c81239a] you can't build ReiNand
Switching to ctrulib build [cf91be5] works fine

**Comment by fox8091** [comment]
This is due to FS changes not yet handled by Rei. It requires changes in 3ds_injector.

**Comment by Reisyukaku** [comment]
fixed
