### ISSUE TITLE
Cant run smash bros and MH4U at old3ds.

### ISSUE THREAD

**Issue by wjuniorst** [Reisyukaku/ReiNand#50]
Hi, 
I havent managed to make the games above run, i made a fresh emunand and i'm opening reinand trough HBC/menuhax, its possible to be a RAM issue? How do i manage to make those work?

**Comment by Reisyukaku** [comment]
It is a ram issue. I'm looking into a clean solution for this since i dont like the current hacky stuff people are doing.

**Comment by wjuniorst** [comment]
I hope it can be fix ir ^^
BTW thanks for the best cfw around i really apreciate your efforts!

**Comment by Reisyukaku** [comment]
should have fixed, will close for now
