### ISSUE TITLE
Change how you give credit on PRs

### ISSUE THREAD

**Issue by ghost** [Reisyukaku/ReiNand#51]
I've at least seen people on other projects thank the person for their work in the commit messages or readme when they reimplement something someone else did. I think it would save you a lot of head aches too in the long run

**Comment by Reisyukaku** [comment]
i give people that help credit. Unless i missed someone, let me know.

**Comment by ghost** [comment]
Alright, I'll let you know if I see anything. I guess I should apologize for thinking there was a problem based on information from other sources. You seem like a pretty nice person actually

**Comment by Reisyukaku** [comment]
Thanks. Those 'other sources' are probably just the haters.
I'll close this for now but feel free to open or comment as needed.
