### ISSUE TITLE
Pokemon Alpha Sapphire always loads shinny pokemon

### ISSUE THREAD

**Issue by ItsSkynet** [Reisyukaku/ReiNand#52]
A friend of mine updated to 4.1 oppened alpha sapphire and shinny pokemon galore started, i assumed he must have been loading a patch with NTR, so we deleted ntr bin just in case, but the galore continued, we fallback to Reinand 4.0 and it fixed the problem, maybe there is a patch in 4.1 that causes that?

Here is the video proof
https://www.youtube.com/watch?v=04O2hg40xSg

**Comment by hax0kartik** [comment]
Well its happening to me also.Maybe due to the RO patches

**Comment by Reisyukaku** [comment]
lolwut? i never added a shiny patch to it

**Comment by Reisyukaku** [comment]
Hmm i think i fixed the 'problem'

**Comment by hax0kartik** [comment]
Had your friend edited his save file with pkhex or pchex??

**Comment by ItsSkynet** [comment]
nope, can a wonder trade pokemon have some stored values that might change that? he does wonder trade almost all day.

**Comment by ItsSkynet** [comment]
BTW, @Reisyukaku Thank you mate for that quick reply and fix.

**Comment by Committee** [comment]
sorry for commenting but O.O will save 4.1 for the shinys!

**Comment by ijhonatan** [comment]
I tried using the 4.1 but that didn't happen to me.... can you send me the files to reproduce the glitch?
darknessworldboy@gmail.com

**Comment by ItsSkynet** [comment]
yeah, gimme a sec
