### ISSUE TITLE
Black screen on boot if patches.dat exists, boots fine if it doesn't

### ISSUE THREAD

**Issue by thedax** [Reisyukaku/ReiNand#53]
Here's my setup, before I describe what's going on:
-A9LH, AuroraWright's no screen init fork & branch
-SysNAND 11.0.0-33U, no emuNAND on SD, no traces of emuNAND leftover, completely fresh format on the SD
-ReiNand 4.1, downloaded from the releases page
-N3DS XL

The problem: if patches.dat exists in /rei/patches, the console boots to only a black screen. If the file is deleted or not there, it works fine.

At first I thought it was related to the hardcoded offsets used to load the CXI itself, but that's not the case. Also, I made this here since the loader repo has no issue tracker, and it seemed silly to make a fork + fake pull request to report it.

**Comment by Reisyukaku** [comment]
Hmm. I was gonna assume the hard coded offset too.. actually wait a min..theres an extra 00 at the end of patches.dat.. delete that and fixed :p 
Not sure why it only effects o3ds though. Strange.

**Comment by Reisyukaku** [comment]
okie, fixed

**Comment by thedax** [comment]
Thanks Rei.
