### ISSUE TITLE
Black screen o3ds 4.5.0-8E Reinand 4.1 Emunand 11.0.0-33E

### ISSUE THREAD

**Issue by DryTaste** [Reisyukaku/ReiNand#59]
Like the title describes,

Original 3ds XL on 4.5.0-8E trying to boot ReiNand 4.1. Emunand 11.0.0-33E loads fine from gateway MSET. But gives black screen when trying to boot ReiNand from MSET.

Used this ROP installer(obviously used different installer for Gateway):
https://github.com/Reisyukaku/rnInstaller

Emunand 4.5 boots fine with ReiNand.

**Comment by Slashin-it-up** [comment]
Try using A9LH.

**Comment by DryTaste** [comment]
I did, A9LH doesn't have any issues. Thanks.
