### ISSUE TITLE
O3DS Freezes on black screen after splash

### ISSUE THREAD

**Issue by codemankey23** [Reisyukaku/ReiNand#60]
I've downloaded ReiNand v4.1 and the firmware.bin from here https://github.com/Reisyukaku/ReiNand/tree/master/data. I also grabbed the new splash.bin and patches folder from there. After it loads the splash screen, I just get stuck at a black screen.

**Comment by Reisyukaku** [comment]
RO patch breaks things if you're compiling from source. Delete ro patch from patches folder until someone can find the bug in the loader module. Or revert back to old loader module that uses patches.dat.

**Comment by Reisyukaku** [comment]
The release has everything already there. Dont add anything. Also if you're upgrading versions, it helps to delete rei folder on SD before copying files over. It wont cause issues, but it cleans up the SD.

**Comment by codemankey23** [comment]
Thanks for the response. The guide I was following must have been outdated. I deleted all the ReiNand stuff I had on my card and reinstalled just 4.1 as is and it worked.
