### ISSUE TITLE
N3ds freezes on black screen 

### ISSUE THREAD

**Issue by Saswelcchi** [Reisyukaku/ReiNand#61]
After I updated on v4.1 copied and replaced the files from it's folder, I boot up my n3ds but after the menuhax loaded it's just plain black screen, reinand won't boot. It's coldboot so it should directly boot to a splash of reinand but it's just a black screen. Help.

Sorry that I'm such a noob but i really don't know what to do at this point considering that i don't know much about stuff like this (being 15 and all)

**Comment by CrimsonMaple** [comment]
Go back to 4.0 and tell me if it boots. Make sure you updated the Rei folder and replaced Reinand.dat.

**Comment by Saswelcchi** [comment]
I followed your instructions but it still won't boot.

Thanks for the help.

**Comment by CrimsonMaple** [comment]
Dang, shot and I missed XD. K try loading from the actual homebrew launcher. The only issues I think it could be, is that the coldboot launcher is busted, quite possible. Or that your sd card is screwed

**Comment by Saswelcchi** [comment]
I remember that i can't access hbl since forever xD
I think that my sd is screwed. So probably that. Since the coldboot launcher is still running before it freezes on black screen where there's supposed to be a reinand splash.

Thanks a lot.
