### ISSUE TITLE
Working On O3DS on 11.2.0-35U (SysNand)?

### ISSUE THREAD

**Issue by Slashin-it-up** [Reisyukaku/ReiNand#62]
I Havent installed emunad, can I install it on 11.2.0-35U

**Comment by CrimsonMaple** [comment]
Not unless you downgrade. Please do direct your questions like this to GBATemp. This is for bugs within the CFW itself. 
TLDR: No. Look to gbatemp for support.

**Comment by Slashin-it-up** [comment]
Ok Thanks.
