### ISSUE TITLE
Hope to update ReiNand~

### ISSUE THREAD

**Issue by JKC-A9LH** [Reisyukaku/ReiNand#63]
Although Luma3DS CFW is very good，l think ReiNand is excellent，too~So Dear Reisyukaku，don't give up to stop updating ReiNand，l like ReiNand thank you~

**Comment by CrimsonMaple** [comment]
This isn't an issue. Move comments to GBATemp from now on. However ReiNand is having an update sometime soon. Rei and I have been working on it for a while.

**Comment by JKC-A9LH** [comment]
Thank you! l will go to GBATemp if l have some questions to ask you! Thank you，l love you and ReiNand~

**Comment by CrimsonMaple** [comment]
No Problem! I would be glad to help in the future.

**Comment by Reisyukaku** [comment]
wish granted :p

**Comment by Jerry-Shaw** [comment]
Good to see you back, aha...
