### ISSUE TITLE
make reinand better than lima3ds :^)

### ISSUE THREAD

**Issue by dd01da0465b4542f8f8af4ecedc149ed** [Reisyukaku/ReiNand#64]
quality shitpost

**Comment by Reisyukaku** [comment]
No can do fam. In order to make it better, it'd have to first be worse then luma ;)

**Comment by Davidosky99** [comment]
only if has ds plaguin and gacube emeleter othrwis luams3d will always b betr than animunand

**Comment by Ram-chan** [comment]
saim

**Comment by pokecraft98** [comment]
only if rei has more limas than mr krabs

**Comment by Davidosky99** [comment]
iom animunand is 2 bloated remove grils and replece with decent cude and luams

**Comment by pokecraft98** [comment]
tru but rei is duh 1 true tig tat B R C C my 3ds

**Comment by Davidosky99** [comment]
I DEMEND LIGHETER CUDE

**Comment by pokecraft98** [comment]
WEN IS SMEA GONNA SUE YA

**Comment by Davidosky99** [comment]
THEY BEN U

**Comment by CrimsonMaple** [comment]
When? When Lima finally gets that first release and I can play melee on my 3ds.

**Comment by Davidosky99** [comment]
meelee hd or rito

**Comment by thunderkai** [comment]
Nee sama nee sama! When will you release RadiumCFW? Looks cewl

**Comment by Davidosky99** [comment]
PLEASE DO IT NAO! NAO!!!! UR OBALATION AS DEV! AND MAKE N64 AND WIII EMALATOR

**Comment by Davidosky99** [comment]
also dotn be homophobe and transphobe its bed

**Comment by Davidosky99** [comment]
@Reisyukaku quik q : what dues reinand hav over lumas?

**Comment by pokecraft98** [comment]
wen is reinand bein added to 3ds.bricks liek wen you had a chioce betwen cake and lima

**Comment by pokecraft98** [comment]
IT WONT

**Comment by pokecraft98** [comment]
BECAUSE ITS

**Comment by pokecraft98** [comment]
OUTDATED

**Comment by pokecraft98** [comment]
PIECES

**Comment by pokecraft98** [comment]
OF

**Comment by pokecraft98** [comment]
CRAP

**Comment by Davidosky99** [comment]
alsu why isnt reinend on 3ds gudie???????

**Comment by Davidosky99** [comment]
IS REI REALLY LAZY DEV?

**Comment by pokecraft98** [comment]
yez

**Comment by Davidosky99** [comment]
damnit i knaw that pedobers were denerous

**Comment by thunderkai** [comment]
*reports for spam*

**Comment by Davidosky99** [comment]
D:

**Comment by pokecraft98** [comment]
dont be a billy

**Comment by Davidosky99** [comment]
❌ ☕️

**Comment by pokecraft98** [comment]
billy are mean

**Comment by Davidosky99** [comment]
no coeffei!
