### ISSUE TITLE
Stuck on Black Screen after Initial Splash screen.

### ISSUE THREAD

**Issue by Committee** [Reisyukaku/ReiNand#65]
N3DS 11.2 Sysnand in A9LH, payload chained Reinand to load when up button is pressed during boot.

rei folder and reinand.dat file on the root of the sd card.

welcome back btw, this was my last go-to cfw before the whole a9lh explosion.

**Comment by Reisyukaku** [comment]
reinand.dat is only for menuhax/mset users. arm9loaderhax.bin is the same thing minus the rop, so you can load via a9lh. I've tested on n3ds and panda unit and cant replicate the issue, but it sounds like it's running anyways. Maybe you have fragments of emunand left on your sd card? try holding start on boot to see if it boots. If so, that might be the issue

**Comment by Committee** [comment]
clean sd card since going a9lh, no trace of emunand left.

one thing though i renamed it to up_reinand.bin to launch it, not sure if that makes a difference

**Comment by Rohul1997** [comment]
Try without chain loading. So put reinand arm9loaderhax.bin file on root and see if it works then.

**Comment by Committee** [comment]
@Rohul1997 tried that too, getting a black screen still

Also when I do this, chan loading does not work anymore, I only get a black screen.

**Comment by Rohul1997** [comment]
ok leave that on the root still and hold start while powering on your 3ds.

**Comment by Committee** [comment]
ok that one loaded.

Any idea why it wouldn't work then chain loading?

EDIT:

Tried to chainload it again using the up button and held the Start button after the initial splashscreen, it went ahead and booted to Reinand.

Question: Why the need to hold the Start Button?

**Comment by Rohul1997** [comment]
Like what Rei said "Maybe you have fragments of emunand left on your sd card?"

**Comment by Committee** [comment]
Alright well, clean sd card like I said, after doing the sd cardless a9lh I reformatted my sd card to make it clean.

I'll leave this at this setup and just hold start when doing Reinand.

Thank you for the help! :1st_place_medal:

**Comment by Rohul1997** [comment]
Just backup all sd files and format the sd card then copy back all files

**Comment by Masamune3210** [comment]
Formatting the SD card will not remove emunand, as it exists on another partition on the card. To remove emunand, either use a PC to remove the extra partition, or use EmuNAND9 to remove the emunand for you
