### ISSUE TITLE
Reinand 5.0 Will boot to this when booted as a Luma Payload.

### ISSUE THREAD

**Issue by Slashin-it-up** [Reisyukaku/ReiNand#66]
This will happen if this is booted as a Luma Payload. (Also if booted by its self, it will boot a black Screen (Also 11.2 USA 2DS)

**Comment by Slashin-it-up** [comment]
Data Abort ARM9 what it is
EDIT: That will happen if the Rei folder is a different version then the ARM9loaderhax.bin it will also boot to a black screen.

**Comment by CrimsonMaple** [comment]
Kinda hard to diagnose issue if I cant tell what it is lol. Maybe try a reinstall.

[edit]: Uhhh. If the /rei folder is outdated ReiNand cant load the new patches. It should be good practice to clean update your CFW every big update.

**Comment by Slashin-it-up** [comment]
Yeah I did re-installing and update. Still leads to a black screen

**Comment by CrimsonMaple** [comment]
Strange. I know there is an issue with ReiNand not booting splash when messing with chainloading on Luma. Ive run into the issue where I cant see splash from RN unless i'm chainloading from corbenik. Try letting it boot for a bit.

[edit] Are you seeing a splash screen at all?

**Comment by Slashin-it-up** [comment]
Yes. I read an issue and I think my SD may have some emunand parts still stuck on it

**Comment by CrimsonMaple** [comment]
Probably, seems to be common issue. Gonna ask Rei to close this. Encase you want it. I made an autoboot sysnand version of Reinand. 
[AutoBoot Sys ReiNand Download](https://www.dropbox.com/s/mrbrn2c2pujcm70/ReiNand-AutoBootSys.zip?dl=0)

**Comment by Slashin-it-up** [comment]
Yea thanks. For some odd reason I can not restore it and remove it thanks any way. Now My sd went from 59.8 to 59.4 because of this
