### ISSUE TITLE
Waiting for your new version of ReiNand to support 11.3

### ISSUE THREAD

**Issue by JKC-A9LH** [Reisyukaku/ReiNand#69]
Thank you for your effort！

**Comment by Satinho** [comment]
Me too! I've updated reinand to 11.3 and I have the black screen when I boot. Is there any progress on a new version?

**Comment by JKC-A9LH** [comment]
@Satinho Yeah, @Reisyukaku and @CrimsonMaple are working on the new version now.

**Comment by darklite404** [comment]
Good news !!!

**Comment by Jerry-Shaw** [comment]
haha, yep. Cannot wait now.

**Comment by Reisyukaku** [comment]
ok, done. that was exhausting.

**Comment by CrimsonMaple** [comment]
[Here](https://www.dropbox.com/s/n1xmnd0q34fsr1o/ReiNand5.1.zip?dl=0) is a link to a compiled build of the latest commit for those of you who need it. Thanks Rei for fixing this! ^^

**Comment by dothackjhe** [comment]
As of posting time, the latest version of ReiNand uploaded for this repository is still version 5. 

How's this version 5.1 different from it? @CrimsonMaple @Reisyukaku

**Comment by CrimsonMaple** [comment]
@dothackjhe, 5.1 has 11.3 support, but broke the reboot patch.

**Comment by dothackjhe** [comment]
@CrimsonMaple What do you mean by "broke the reboot patch?"

**Comment by CrimsonMaple** [comment]
@dothackjhe no extended memory games for o3ds on 11.3

**Comment by dothackjhe** [comment]
@CrimsonMaple I did not know there was such a thing for the O3DS. I thought a matter such as that is for the N3DS.
