### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by povka** [Reisyukaku/ReiNand#71]
Hello, I'm new to 3ds modding and I don't understand almost nothing (My friend modded my 2ds). Basically today I updated my EmuNAND and after restarting it's stuck on black screen. Tried restarrting with no help. It shows ReiNAND splash screen, then black screen lits up, and stays black. I would upload a video, but it doesn't let me upload anything above 10MB

**Comment by CrimsonMaple** [comment]
Are you using the latest commit?

**Comment by povka** [comment]
I know I sound like a noob, but I have no idea what commit is (So most likely I'm using outdated). I was using this 2ds more than half a year, constantly updating and using homebrew for pokemon genning with no problem, but know it doesn't boot into emunand after I updated today.
If you can, could you explain in some way a person with no experience on this kind of stuff would understant?

**Comment by CrimsonMaple** [comment]
A commit is an update to the source code. The latest one fixed 11.3 firm loading. [Here](https://www.dropbox.com/s/n1xmnd0q34fsr1o/ReiNand5.1.zip?dl=0) is a link to the latest compiled commit. In the future if the latest version doesnt address the issue go to the GBAtemp thread and look for "nightlies". I usually post them when an important issue is resolved there.
