### ISSUE TITLE
ReiNand and 11.4 firmware

### ISSUE THREAD

**Issue by dothackjhe** [Reisyukaku/ReiNand#72]
Any word regarding the compatibility between ReiNand 5.0.1 and the freshly released 11.4 firmware update?

**Comment by CrimsonMaple** [comment]
Rei just pushed a commit that added 11.4 support. Just download the firmware.bin and drop it in the /rei folder.

**Comment by darklite404** [comment]
Confirm that , Rei work well on 11.4.0-37J

**Comment by dothackjhe** [comment]
Crimson says to download the latest commit of firmware.bin and put it inside rei folder at the root of your SD card. By then can you safely update ReiNand's Emunand firmware to 11.4 without complications.
