### ISSUE TITLE
Screen hangs after loading homescreen

### ISSUE THREAD

**Issue by kfrabida** [Reisyukaku/ReiNand#75]
I experienced the black screen after updating to the latest firmware so I downloaded the latest release. Homescreen loads but the battery and other stuff at the top are not showing, but the game icon loads. When I attempt to launch a game, the screen hangs. Not sure what to do. Thanks.

**Comment by CrimsonMaple** [comment]
Download the latest Firmware.bin from the github. That will fix your issue.
