### ISSUE TITLE
Reinand freezez whenever I start any game / apps after updating to 5.1

### ISSUE THREAD

**Issue by hw121693** [Reisyukaku/ReiNand#76]
Can someone please tell me what to do..?
After I click system update, I am unable to open any app / game including the system setup

**Comment by CrimsonMaple** [comment]
Same issue as #73

**Comment by CrimsonMaple** [comment]
correction, just update to the firmware.bin in the repository. navagate to data and click on firmware.bin. Then download it and put it in /rei
