### ISSUE TITLE
kill reinand from b9s

### ISSUE THREAD

**Issue by dd01da0465b4542f8f8af4ecedc149ed** [Reisyukaku/ReiNand#78]
not like anyone uses reinand anymore.

**Comment by CrimsonMaple** [comment]
I respectfully disagree with you, and do not want to deal with this drama. I am closing this thread. Do not discuss anything on GitHub. Go to the appropriate place for this.

**Comment by GabrielRRussell** [comment]
Okay, here is the issue with comments like this. Even if Reinand is less popular than Luma, (which I bet it is) this is still a project to work on. My repos aren't helpful to the scene in any way, I just use them to experiment and open source some stuff. I think it's pretty neat that we have the choice of multiple CFW's, and it should be that way, in case Aurora stops updating Luma.
