### ISSUE TITLE
System Freezes when I open any app.

### ISSUE THREAD

**Issue by alfredogomez35** [Reisyukaku/ReiNand#79]
I updated to 11.4 and it boots fine but the system locks up when trying to open any app.

**Comment by CrimsonMaple** [comment]
Download the firmware.bin from /data on the repository.

**Comment by alfredogomez35** [comment]
Thanks so much! Have an AWESOME day!

**Comment by alfredogomez35** [comment]
Hey, I have another issue. Boot ntr won't boot. I downloaded the newest version but it forces a restart when I open it. Would you know anything about that?

**Comment by CrimsonMaple** [comment]
@alfredogomez35 no k11 backdoor. I'm adding it in the next release with SigHax support as well.

**Comment by alfredogomez35** [comment]
Alrighty, thanks so much for your help!
