### ISSUE TITLE
Where do I put the files???

### ISSUE THREAD

**Issue by Picahaxer** [Reisyukaku/ReiNand#80]
I don't know where to put the files. Can someone help?

**Comment by CrimsonMaple** [comment]
You are going to have to be more specific. The whole CFW goes on the SD card. Firmware.bin downloaded from /data goes into /rei folder.

**Comment by Picahaxer** [comment]
what file goes where? also I have a 11.4.0-37U new 3ds. will this even work?

**Comment by Picahaxer** [comment]
to be more exact, where does the CFW go into? does it go onto the root or in the 3ds folder?

**Comment by CrimsonMaple** [comment]
First. Do you have arm9loaderhax or boot9Strap? And I just told you where all the files went. They go on the Root

**Comment by Picahaxer** [comment]
I use Ninjahax

**Comment by Picahaxer** [comment]
also I didn't see that, sorry

**Comment by Picahaxer** [comment]
anyway, I have it on my root. what now?
I already tried putting it there and it didn't work.

**Comment by CrimsonMaple** [comment]
Do you have a sysnand on 9.2? Because if you are sysnand 11.4 you can't use any CFW.

**Comment by Picahaxer** [comment]
sysnand? i'm new to homebrew.
what is a sysnand?

**Comment by CrimsonMaple** [comment]
System NAND. Where the firmware is booted. Your reaction just gave the the picture. You cannot install any CFW without a physical mod or another hacked 3ds with a legal copy of one of the dsiware games. Sorry. I'm closing the thread.

**Comment by Picahaxer** [comment]
arrgh

**Comment by CrimsonMaple** [comment]
Follow the guide when you do though. [Here is a hyperlink to it.](3ds.guide)
