### ISSUE TITLE
ReiNand 5.1 black screen

### ISSUE THREAD

**Issue by Guineh** [Reisyukaku/ReiNand#81]
I've just updated ReiNand and emuNand to the last version but when I try to start ReiNand it keepts in an infinite black screen. Some help?

PD: Sorry for my english, im from spain

**Comment by CrimsonMaple** [comment]
Change the firmware.bin in /rei to the one in /data on GitHub. I've said this in many other issues.

**Comment by Guineh** [comment]
It doesn't work

**Comment by CrimsonMaple** [comment]
What entry point are you using?
