### ISSUE TITLE
Freezes on 3dsx version

### ISSUE THREAD

**Issue by xXPhartyGhamerXx** [Reisyukaku/ReiNand#83]
When I run Reinand on the 3dsx version it freezes (my nintendo version is 11.5.0-38E) showsa blackscreen and When I reboot my console is not Reinand

**Comment by CrimsonMaple** [comment]
Are you using the firmware binary on the repo and not the one on the release zip? I might have to fix haxloader.

**Comment by Slashin-it-up** [comment]
@CrimsonMaple He is on a incompatible firmware for 3DSX. 

@xXPhartyGhamerXx You need 9.0-9.2 to use the 3DSX version. The only ones that will work on 11.5 is B9S and A9LH

**Comment by xXPhartyGhamerXx** [comment]
Thank you

**Comment by xXPhartyGhamerXx** [comment]
and then.. How do I install it?

**Comment by Slashin-it-up** [comment]
Use 3DS.guide. Then when you are done, switch the boot.firm with the one https://gbatemp.net/threads/source-release-reinand-cfw.394309/page-306#post-7384380

**Comment by xXPhartyGhamerXx** [comment]
Thx
