### ISSUE TITLE
Home menu freezing

### ISSUE THREAD

**Issue by ghost** [Reisyukaku/ReiNand#84]
I have Reinand 5.1 installed on a 11.5 EmuNAND. The update process went smoothly and the home menu boots but as soon as I fue to open anything (browser, games, apps) the home menu freezes while the menu music is still being played. I dont know if that's an issue with the CFW, I only post it here because I'm asking for help.

Thanks you

**Comment by CrimsonMaple** [comment]
Download firmware.bin from, /data on the repository and put it in /rei

**Comment by ghost** [comment]
Wow, thank you very much!!!!!!
Can't believe such a simple thing would solve the problem. Was it because the firmware.bin got corrupted while updating?

**Comment by CrimsonMaple** [comment]
No, it's an older native_firm that shouldn't be booted. The one on the repo is from 11.4 and is the latest Native_Firm revision.
