### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by TomG-Official** [Reisyukaku/ReiNand#87]
I have no idea how to get it too run or working any help?
i have a old 3ds new 3ds and a new 2ds all luma cfw 11.6 
i was trying to get a emunand for my old 3ds

**Comment by CrimsonMaple** [comment]
If you have b9s go over to my repo. Rei-Six. However I fucked up emunand support on my open beta. You can use an emunand with Luma it's a setting in the config. Anyways, there is almost zero reason to use emunand anymore. It's just as safe as sysnand.
