### ISSUE TITLE
Can I install on O3DS XL original FW 11.6?

### ISSUE THREAD

**Issue by sandgamerx** [Reisyukaku/ReiNand#89]
Hello
I have friend had a o3ds XL with original fw 11.6.
Can this cfw installed on those o3ds XL?

**Comment by CrimsonMaple** [comment]
Please, do not ask support questions on Github. It's best to ask questions like this on the [Gbatemp forum](https://gbatemp.net/threads/source-release-reinand-cfw.394309/). I am more than happy to help you there.
