### ISSUE TITLE
[Feature Req.] Support for N3DS 178MB memory layout/mode

### ISSUE THREAD

**Issue by thedax** [Reisyukaku/ReiNand#9]
Supposedly the guys in #3dsdev have this on their CFWs, and the extra memory would be nice for emulators that can use large games, such as MAME or NeoGeo emulators, along with other homebrew apps. When you try to run a CIA that indicates this memory layout, the 3DS will reboot and then display the generic black "Error has occurred. Turn the power off." screen.

Consider it low priority though.

**Comment by thedax** [comment]
Come to think of it, I wonder if this mode is similar to how the old 3DS boots Smash Bros./MH4U, and needs a "reboot patch" to solve it. I wonder how difficult it'd be to compare where the old 3DS patches happen and see if I can find where it might happen on N3DS..

**Comment by Reisyukaku** [comment]
I looked into it a few days ago, and it seems like an arm11 thing.. config memory is a virtual address.

**Comment by thedax** [comment]
Do you think it's something a homebrew app could be written to do in the mean-time (to change the memory layout, then maybe run another homebrew)? I did notice that the wiki (3dbrew) mentioned that stuff is read-only though. Bummer.

**Comment by Reisyukaku** [comment]
I was thinking maybe modifying ntr or patching the arm 11 kernel or whatever writes to that config mem.

**Comment by thedax** [comment]
Looks like AuroraWright got it figured out with some help, it needs a reboot patch:

https://github.com/AuroraWright/AuReiNand/commit/23fd26630fddb94c5ccd9e30ae379c8c841373fd
https://github.com/AuroraWright/AuReiNand/commit/e74eda16cef37431cc8efa73ebb5cf1a40380439

**Comment by Reisyukaku** [comment]
i'd never add reboot patch lol. Like i said, cleanest way is ARM11. I just need to find the time.

**Comment by thedax** [comment]
It could be temporary, but I'll respect that and not press for it.

**Comment by Reisyukaku** [comment]
I think i have an idea so maybe next commit lol

**Comment by CrimsonMaple** [comment]
Fixed on local <3
