### ISSUE TITLE
Are you salty?

### ISSUE THREAD

**Issue by Multimegamander** [Reisyukaku/ReiNand#90]
Everyone is telling me that you're really mad because I killed Chaos xDD

**Comment by favna** [comment]
What is there to be salty about lol. We had everything backed up. You’re the salty kid here, not Rei nor I.

**Comment by ghCadia** [comment]
#nicememe

**Comment by Reisyukaku** [comment]
I don't recall ever responding on that situation. Fake news.

**Comment by thunderkai** [comment]
Hi multi! How’s that Yoshi dick tasting?

**Comment by CrimsonMaple** [comment]
Don't start drama. Go to the proper channels to do so. I don't want to see things like this in my email. I'm locking this.
