### ISSUE TITLE
Does ReiNand work with 3ds update 11.7.0-40

### ISSUE THREAD

**Issue by CJ3510** [Reisyukaku/ReiNand#92]
I still have 10.4 downloaded on my 3ds but, I would like to update to 11.7.0-40. I am just nervous that my 3ds could break. I really want to be able to use internet services again. So, if someone can answer my question it would be greatly appreciated.

**Comment by Reisyukaku** [comment]
I dont see any reason why things would break. I made this pretty future proof.

**Comment by CrimsonMaple** [comment]
Duplicate of #88 
Both versions use the same firmware.bin
